### ISSUE TITLE
HTTP testing

### ISSUE THREAD

**Issue by enilsen16** [enilsen16/urban_pass#17]
https://github.com/vcr/vcr

**Comment by sentientmonkey** [comment]
VCR may be the easiest drop-in replacement for you - the first time it runs, it generates fixture data for you, then relies on it going forward. You will have the same static data each run, so that may or may not be what you want.

Other alternatives would be stubbing out the open method. You can use stub in minitest or just redefine that method. That would be something like...

```
 before do
  @urban = UrbanPass::Generate.new
  @urban.define_singleton_method(:open) do
    File.open("fixtures/random_word.html") 
  end
  @word = @urban.generate_word
 end
```

But you may really want to test specific cases, so you might want to create test methods for different words and fixtures. This will help you test various use cases for different words in case the pages vary.

**Comment by enilsen16** [comment]
Thank you @sentientmonkey :+1:
